language: node_js
node_js:
  - '8'
jobs:
  include:
    - stage: Tests
      name: "Unit Tests"
      script:
        - npm run lint
        - npm run test
    - stage: Deploy to Website
      script: skip
      deploy:
        provider: script
        script:
          - echo "Running deployment"
          - npm run doc
          - bash ./utils/deploy-docs.sh
        on:
          branch: travis-ci