language: node_js
node_js:
  - '8'
env:
  global:
    - RELEASE_NAME=ace-components
jobs:
  include:
    - stage: Tests
      name: "Unit Tests"
      script:
        - npm run lint
        - npm run test
    - stage: Deploy
      name: "Deploy Documentation"
      script: skip
      if: branch = master AND type != pull_request
      deploy:
        skip_cleanup: true
        provider: script
        script: bash .utils/deploy-docs.sh
        on:
          branch: master
          repo: ucsd-cse112/The-Ace-Project
          condition: $TRAVIS_PULL_REQUEST = false
    - name: "Deploy to Github Release"
      script: skip
      if: branch = master AND type != pull_request
      before_deploy:
        - npm run minify
        - bash ./.utils/deploy-github.sh
      deploy:
        skip_cleanup: true
        provider: releases
        api_key: "$GITHUB_KEY"
        file: $RELEASE_NAME-$TRAVIS_TAG.tar.gz
        draft: true
        on:
          branch: master
          tags: true
